spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_finder
    username: antonfedoseev
    password:
  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql=TRACE:








